- name: Install python-psutil package
  apt: name=python-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/sergiy/.wallpaper.jpg owner=sergiy group=sergiy mode=600

- name: Set GNOME Wallpaper
  become_user: sergiy
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/sergiy/.wallpaper.jpg'"
