- name: Install git
  apt: name=git-all

- name: Install python
  apt: name=python-devel

- name: Install htop
  apt: name=htop

- name: Install mc
  apt: name=mc

- name: Install tmux
  apt: name=tmux

- name: Install npm
  apt: name=npm

- name: Install vim
  apt: name=vim
